from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setGeometry(300, 200, 611, 385)
        MainWindow.setStyleSheet("*{\n"
                                 "border: none\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:rgb(38, 44, 49);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.extras = QtWidgets.QFrame(self.centralwidget)
        self.extras.setMaximumSize(QtCore.QSize(200, 16777215))
        self.extras.setStyleSheet("background-color:rgba(38, 44, 49, 0.3);")
        self.extras.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.extras.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.extras.setObjectName("extras")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.extras)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.extras)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_10)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 3, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setMaximumSize(QtCore.QSize(70, 70))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../../../.designer/backup/gmail-icon-1.svg"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.verticalLayout_5.addWidget(self.logo, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("QToolBox{\n"
                                   "background-color: rgba(24, 24, 36, 0.8);\n"
                                   "text-align: left;\n"
                                   "}\n"
                                   "QToolBox::tab{\n"
                                   "border-radius: 5px;\n"
                                   "background-color: rgba(17, 16, 26, 0.3);\n"
                                   "text-align: left;\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.file = QtWidgets.QToolBox(self.frame_2)
        self.file.setStyleSheet("color:rgb(255, 255, 255)")
        self.file.setObjectName("file")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 182, 290))
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setStyleSheet("QPushButton#pushButton_5{\n"
                                        "background-color: rgb(255, 88, 127);\n"
                                        "border-radius: 3px}\n"
                                        "\n"
                                        "QPushButton#pushButton_5:hover{\n"
                                        "background-color:rgba(255, 88, 127, 0.4)\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_9.addWidget(self.pushButton_5)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMaximumSize(QtCore.QSize(90, 50))
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
                                      "background-color: rgb(255, 88, 127);\n"
                                      "border-radius: 3px}\n"
                                      "\n"
                                      "QPushButton#pushButton:hover{\n"
                                      "background-color: rgba(255, 88, 127, 0.4)\n"
                                      "}\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_9.addWidget(self.pushButton)
        self.verticalLayout_7.addWidget(self.frame_3, 0, QtCore.Qt.AlignTop)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/arrow-down.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.file.addItem(self.page, icon, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 182, 290))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4{\n"
                                        "background-color: rgb(255, 88, 127);\n"
                                        "border-radius: 3px}\n"
                                        "\n"
                                        "QPushButton#pushButton_4:hover{\n"
                                        "background-color:rgba(255, 88, 127, 0.4)\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_10.addWidget(self.pushButton_4)
        self.verticalLayout_8.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.etc = QtWidgets.QLabel(self.page_2)
        self.etc.setStyleSheet("color:rgb(255, 255, 255)")
        self.etc.setWordWrap(True)
        self.etc.setObjectName("etc")
        self.verticalLayout_8.addWidget(self.etc)
        self.file.addItem(self.page_2, icon, "")
        self.verticalLayout_6.addWidget(self.file)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.horizontalLayout.addWidget(self.extras)
        self.main = QtWidgets.QFrame(self.centralwidget)
        self.main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main.setObjectName("main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.main)
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.header)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minimize = QtWidgets.QPushButton(self.frame_6)
        self.minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("arrow-down-left.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimize.setIcon(icon1)
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_5.addWidget(self.minimize)
        self.maximize = QtWidgets.QPushButton(self.frame_6)
        self.maximize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("maximize-2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.maximize.setIcon(icon2)
        self.maximize.setObjectName("maximize")
        self.horizontalLayout_5.addWidget(self.maximize)
        self.close = QtWidgets.QPushButton(self.frame_6)
        self.close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close.setIcon(icon3)
        self.close.setObjectName("close")
        self.horizontalLayout_5.addWidget(self.close)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.header, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.body = QtWidgets.QFrame(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.body.sizePolicy().hasHeightForWidth())
        self.body.setSizePolicy(sizePolicy)
        self.body.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.body.setObjectName("body")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_11.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_11.setSpacing(3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_5 = QtWidgets.QFrame(self.body)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.website = QtWidgets.QLineEdit(self.frame_5)
        self.website.setMaximumSize(QtCore.QSize(410, 16777215))
        self.website.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-radius: 3px;")
        self.website.setObjectName("website")
        self.verticalLayout_12.addWidget(self.website)
        self.verticalLayout_11.addWidget(self.frame_5, 0, QtCore.Qt.AlignBottom)
        self.frame_7 = QtWidgets.QFrame(self.body)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.result = QtWidgets.QTextBrowser(self.frame_7)
        self.result.setStyleSheet("border-radius: 3px;\n"
                                  "background-color: rgb(255, 255, 255);")
        self.result.setObjectName("result")
        self.verticalLayout_13.addWidget(self.result, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_11.addWidget(self.frame_7)
        self.frame_11 = QtWidgets.QFrame(self.body)
        self.frame_11.setMaximumSize(QtCore.QSize(70, 59))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.start_button = QtWidgets.QPushButton(self.frame_11)
        self.start_button.setMinimumSize(QtCore.QSize(45, 30))
        self.start_button.setStyleSheet("QPushButton#start_button{\n"
                                        "background-color: rgb(92, 100, 116);\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "border-radius: 3px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton#start_button:hover{\n"
                                        "background-color: rgba(72, 100, 86, 0.7);\n"
                                        "}")
        self.start_button.setObjectName("start_button")
        self.verticalLayout_14.addWidget(self.start_button)
        self.verticalLayout_11.addWidget(self.frame_11, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.body)
        self.footer = QtWidgets.QFrame(self.main)
        self.footer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.footer)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.made_by = QtWidgets.QLabel(self.frame_8)
        self.made_by.setStyleSheet("QLabel#made_by{\n"
                                   "color: rgb(255, 0, 0);}\n"
                                   "\n"
                                   "QLabel#made_by:hover{\n"
                                   "color:rgb(255, 0, 70)\n"
                                   "}")
        self.made_by.setObjectName("made_by")
        self.verticalLayout_3.addWidget(self.made_by)
        self.horizontalLayout_2.addWidget(self.frame_8, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignBottom)
        self.resizer = QtWidgets.QFrame(self.footer)
        self.resizer.setMinimumSize(QtCore.QSize(10, 10))
        self.resizer.setMaximumSize(QtCore.QSize(10, 10))
        self.resizer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.resizer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.resizer.setObjectName("resizer")
        self.horizontalLayout_2.addWidget(self.resizer)
        self.verticalLayout.addWidget(self.footer, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.file.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "New"))
        self.pushButton_5.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.pushButton.setText(_translate("MainWindow", "End Process"))
        self.pushButton.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.file.setItemText(self.file.indexOf(self.page), _translate("MainWindow", "File"))
        self.pushButton_4.setText(_translate("MainWindow", ".csv"))
        self.etc.setText(_translate("MainWindow", "More features will be available in the next update..."))
        self.file.setItemText(self.file.indexOf(self.page_2), _translate("MainWindow", "Export to"))
        self.website.setPlaceholderText(_translate("MainWindow", "Type/Paste Website Link Here"))
        self.result.setPlaceholderText(_translate("MainWindow", "Results will be shown here"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.start_button.setShortcut(_translate("MainWindow", "Return"))
        self.made_by.setText(_translate("MainWindow", "Extractor v 1.0 by SIEG"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
